#!/bin/bash
#
# MIT License
#
# Copyright (c) 2022 Aptivi
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

if ! command -v tput &> /dev/null; then
        AQUA=""
	ORANGE=""
	RESET=""
else
	AQUA=$(tput setaf 45)
	ORANGE=$(tput setaf 214)
	RESET=$(tput sgr0)
fi

enum_and_push() { 
	universal_commit_msg=$2
	[[ -z $2 ]] && universal_commit_msg="General changes"
        readarray -t maybe_gits < <( find "$1" -maxdepth 1 -name "*" -type d )
	for maybe_git in "${maybe_gits[@]}"
	do
		if [[ ! -e "$maybe_git/.git" ]]; then
                    echo "${ORANGE}[*] ${RESET}Repo $maybe_git is not a git repo. Refusing to push..."
                    continue
                fi
		echo "${AQUA}[+] ${RESET}Pushing to $maybe_git..."
		git -C $maybe_git add -A .
		git -C $maybe_git commit -m "$universal_commit_msg"
		git -C $maybe_git push
		echo "${AQUA}[+] ${RESET}Push of $maybe_git done."
	done
}

if [[ -z $1 ]]; then
        echo "${ORANGE}[!] ${RESET}Specify git directory containing all repositories and, optionally, a universal commit message."
else
        enum_and_push $1 "$2"
fi
